version: '3.8'
services:
  web:
    build: .
    ports:
      - '5000:80'
#  db:
#    image: postgres:14.1
#    container_name: pgdb
#    restart: always
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=postgres
#    ports:
#      - '5432:5432'
#    volumes:
#      - db:/var/lib/postgresql/data
#      - ./db:/docker-entrypoint-initdb.d/
#volumes:
#  db:
#    driver: local
